#:schema node_modules/wrangler/config-schema.json
name = "rss-bridge"
compatibility_date = "2024-06-14"
pages_build_output_dir = ".svelte-kit/cloudflare"

[env.production.vars]
NODE_VERSION = "20.12"
NPM_VERSION = "10"
